### ISSUE TITLE
[Bug]: Starting Game Error "Renderer Not Initialized"

### ISSUE THREAD

**Issue by Nice1m8** [nonamecrackers2/simple-clouds#103]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

0.6.3

### Mod Loader

Forge

### Mod Loader Version

Forge 47.3.22

### Describe the Bug

When ever I start Minecraft with Simple Clouds installed I get the same crash message saying "java.lang.NullPointerException: Renderer not initialized!"

### Steps to Reproduce

1. Have Simple Clouds installed
2. Start Minecraft

### Crash Reports/Logs

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2024-12-25 13:58:51
Description: Initializing game

java.lang.NullPointerException: Renderer not initialized!
	at java.util.Objects.requireNonNull(Objects.java:235) ~[?:?] {}
	at dev.nonamecrackers2.simpleclouds.client.renderer.SimpleCloudsRenderer.getInstance(SimpleCloudsRenderer.java:1160) ~[simpleclouds-0.6.3+1.20.1-forge-all.jar%23152!/:0.6.3+1.20.1-forge] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.GameRenderer.handler$zze000$simpleclouds$resizeRenderer_resize(GameRenderer.java:2109) ~[client-1.20.1-20230612.114412-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crackerslib.mixins.json:MixinGameRendererAccessor,pl:mixin:APP:simpleclouds.mixins.json:MixinGameRenderer,pl:mixin:APP:simpleclouds.mixins.json:MixinGameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109097_(GameRenderer.java:684) ~[client-1.20.1-20230612.114412-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crackerslib.mixins.json:MixinGameRendererAccessor,pl:mixin:APP:simpleclouds.mixins.json:MixinGameRenderer,pl:mixin:APP:simpleclouds.mixins.json:MixinGameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_5741_(Minecraft.java:1279) ~[client-1.20.1-20230612.114412-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:simpleclouds.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:548) ~[client-1.20.1-20230612.114412-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:simpleclouds.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1-forge-47.3.22.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.22.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.22.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.22.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Simple Clouds (simpleclouds), Version: 0.6.3+1.20.1-forge
		Issue tracker URL: https://github.com/nonamecrackers2/simple-clouds/issues
		at TRANSFORMER/simpleclouds@0.6.3+1.20.1-forge/dev.nonamecrackers2.simpleclouds.client.renderer.SimpleCloudsRenderer.getInstance(SimpleCloudsRenderer.java:1160)
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:235) ~[?:?] {}
	at dev.nonamecrackers2.simpleclouds.client.renderer.SimpleCloudsRenderer.getInstance(SimpleCloudsRenderer.java:1160) ~[simpleclouds-0.6.3+1.20.1-forge-all.jar%23152!/:0.6.3+1.20.1-forge] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.GameRenderer.handler$zze000$simpleclouds$resizeRenderer_resize(GameRenderer.java:2109) ~[client-1.20.1-20230612.114412-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crackerslib.mixins.json:MixinGameRendererAccessor,pl:mixin:APP:simpleclouds.mixins.json:MixinGameRenderer,pl:mixin:APP:simpleclouds.mixins.json:MixinGameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109097_(GameRenderer.java:684) ~[client-1.20.1-20230612.114412-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crackerslib.mixins.json:MixinGameRendererAccessor,pl:mixin:APP:simpleclouds.mixins.json:MixinGameRenderer,pl:mixin:APP:simpleclouds.mixins.json:MixinGameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_5741_(Minecraft.java:1279) ~[client-1.20.1-20230612.114412-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:simpleclouds.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:548) ~[client-1.20.1-20230612.114412-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:simpleclouds.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1-forge-47.3.22.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.22.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.22.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.22.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Mac OS X (aarch64) version 15.1.1
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 279559072 bytes (266 MiB) / 503316480 bytes (480 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M3
	Identifier: Apple Inc. Family 0xfa33415e Model 0 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M3
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 9216.00
	Virtual memory used (MB): 5910.06
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 141.00
	JVM Flags: 7 total; -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.20.1-forge-47.3.22
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Apple M3 GL version 4.1 Metal - 89.3, Apple
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x Apple M3
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.22.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.22.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.22.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.22.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.22.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		crackerslib-forge-1.20.1-0.4.4.jar                |CrackersLib                   |crackerslib                   |1.20.1-0.4.4        |NONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.3.22-universal.jar                |Forge                         |forge                         |47.3.22             |NONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		simpleclouds-0.6.3+1.20.1-forge-all.jar           |Simple Clouds                 |simpleclouds                  |0.6.3+1.20.1-forge  |NONE      |Manifest: NOSIGNATURE

### Mod List

NONE

**Comment by nonamecrackers2** [comment]
Looks like you’re using a mac. Macs are currently not supported https://github.com/nonamecrackers2/simple-clouds/issues/14
